server.port=${PORT:8080}
logging.level.org.atmosphere = warn
spring.mustache.check-template-location = false

# Launch the default browser when starting the application in development mode
vaadin.launch-browser=true
# To improve the performance during development.
# For more information https://vaadin.com/docs/latest/integrations/spring/configuration#special-configuration-parameters
vaadin.allowed-packages = com.vaadin,org.vaadin,com.prosegur.spinventory
spring.jpa.defer-datasource-initialization = true


# Configuración de HSQLDB para persistir en disco
spring.datasource.url=jdbc:hsqldb:file:./data/mydatabase
spring.datasource.driverClassName=org.hsqldb.jdbc.JDBCDriver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.HSQLDialect
spring.hsqldb.console.enabled=true


# Configuración de JPA para crear tablas automáticamente
spring.jpa.hibernate.ddl-auto=update

# Configuración para ejecutar scripts SQL al iniciar la aplicación
spring.sql.init.mode=never
spring.hsqldb.console.path=/hsqldb-console


spring.security.password.encoder=org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder

# Enable debug logging
logging.level.org.springframework.boot=DEBUG
